### ISSUE TITLE
Hamburger menu doesn't animate properly when logged out

### ISSUE THREAD

**Issue by Bruncky** [Bruncky/SeeQL#151]
**Describe the bug**
When clicking the hamburger menu, the animation doesn't work properly (GIF provided) when you're logged out.

**To Reproduce**
1. Make sure you are logged out
2. Click on the hamburger menu in the top right corner
3. See error

**Reproducible:** Every time

**Expected behavior**
The menu icon should animate to a cross and then back to the hamburger when clicking again.

**Video**
![Hamburger Menu Bug](https://user-images.githubusercontent.com/19660394/78366330-a293fe80-75c0-11ea-87dd-0b22ba9ad2b8.gif)

**Comment by tim4boom** [comment]
Big fixed
